spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PropertyViewingDB
    username: postgres
    password: Alade@95
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

openai:
  api:
    key: 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
    model: gpt-4-turbo-preview
    temperature: 0.7
    max-tokens: 2000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 